
version: '3'
services:
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: santepam
      MONGO_INITDB_ROOT_PASSWORD: root@covid19&ht
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: ~ 
